import os
import json
import re
from app.agents.state import AgentState
from app.pdf_generator.legal_notices import generate_section_94_bnss_pdf, generate_section_79_it_act_takedown_pdf

def synthesis_node(state: AgentState) -> dict:
    """
    Synthesis Node.
    Compiles specialist drafts, cross-case linkages, and outputs Master FIR summary.
    Dynamically extracts entity-specific investigation steps and generates distinct, individual legal PDF notices per request.
    Strictly preserves exact SOP references generated by specialists without injecting hardcoded string fallbacks.
    """
    case_number = state.get('case_number') or 'CR-2026-9910'
    bns_draft = state.get('bns_draft') or {}
    bsa_draft = state.get('bsa_draft') or {}
    cyber_draft = state.get('cyber_draft') or {}
    conv_draft = state.get('conventional_draft') or {}
    cross_matches = state.get('cross_case_matches') or []
    entities = state.get('entities') or {}
    crime_category = state.get('crime_category') or 'CYBER'
    crime_sub_type = state.get('crime_sub_type') or 'Police Investigation'
    complaint_text = state.get('translated_text') or state.get('complaint_text') or ''
    evaluation_degraded = state.get('evaluation_degraded') or False
    unresolved_feedback = state.get('evaluation_feedback') or []
    
    # 1. Master FIR Details & Grounded Legal Sections (Strict exact compilation)
    bns_sections = bns_draft.get('bns_sections') or []
    sections_list = []
    for s in bns_sections:
        if isinstance(s, dict) and s.get('code'):
            sections_list.append(s.get('code'))
        elif isinstance(s, str):
            sections_list.append(s)
            
    sec_str = ", ".join(sections_list) if sections_list else "Under Investigation"
    
    master_fir = {
        "case_number": case_number,
        "fir_number": f"FIR-{case_number[-4:]}/2026",
        "sections": sec_str,
        "cognizability": bns_draft.get('cognizability'),
        "punishment": bns_draft.get('punishment_duration'),
        "summary": f"Investigation into {crime_sub_type} under sections {sec_str}."
    }
    
    # 2. Consolidated Dynamic Investigation Steps (Exact SOP references, no hardcoded string defaults)
    steps = []
    step_idx = 1
    
    digital_directives = cyber_draft.get('digital_directives') or []
    for directive in digital_directives:
        if isinstance(directive, dict):
            steps.append({
                "step_number": step_idx,
                "title": directive.get("title"),
                "description": directive.get("description"),
                "category": directive.get("category") or "CYBER",
                "sop_reference": directive.get("sop_reference")
            })
        elif isinstance(directive, str):
            steps.append({
                "step_number": step_idx,
                "title": f"Digital Tracing Directive ({crime_sub_type})",
                "description": directive,
                "category": "CYBER",
                "sop_reference": None
            })
        step_idx += 1

    # Money Trail Tracing Step — trace the full end-to-end fund flow from ingestion entities
    money_trail = entities.get('money_trail') or []
    if money_trail:
        hops = []
        for mt in money_trail:
            if isinstance(mt, dict):
                hops.append(
                    f"{mt.get('from_account')} → {mt.get('to_account')} "
                    f"(₹{mt.get('amount')}, {mt.get('method')}, {mt.get('date')})"
                )
        if hops:
            steps.append({
                "step_number": step_idx,
                "title": "Money Trail Tracing & End-to-End Fund Flow Analysis",
                "description": (
                    "Trace the full transfer chain of the defrauded amount: " + " → ".join(hops)
                    + ". Obtain outward + inward statements for each hop, issue Section 94 BNSS notices "
                    "for KYC/IP/device metadata, debit-freeze every mule account, and identify the final "
                    "withdrawal point (ATM / cash-out / crypto exchange) for seizure and forensic imaging."
                ),
                "category": "CYBER",
                "sop_reference": None
            })
            step_idx += 1

    field_steps = conv_draft.get('field_steps') or []
    for step in field_steps:
        if isinstance(step, dict):
            steps.append({
                "step_number": step_idx,
                "title": step.get("title"),
                "description": step.get("description"),
                "category": step.get("category") or "FIELD",
                "sop_reference": step.get("sop_reference")
            })
        elif isinstance(step, str):
            steps.append({
                "step_number": step_idx,
                "title": f"Field Action ({crime_sub_type})",
                "description": step,
                "category": "FIELD",
                "sop_reference": None
            })
        step_idx += 1

    # 3. Dynamic Targeted Legal Requisitions & Individual PDF Generation
    phone_numbers = entities.get('phone_numbers') or []
    vpas = entities.get('vpas_upis') or []
    bank_accounts = entities.get('bank_accounts') or []
    
    legal_requests = []
    pdf_dir = os.path.join(os.getcwd(), "generated_pdfs")
    os.makedirs(pdf_dir, exist_ok=True)

    # A. Targeted Bank Requisitions (Debit Freeze for Accused Accounts, Statement for Victim Accounts)
    for bank_info in bank_accounts:
        if isinstance(bank_info, dict):
            acc_num = bank_info.get('account_number') or 'Suspect Account'
            bank_name = bank_info.get('bank') or 'Bank Nodal Cell'
            ifsc = bank_info.get('ifsc') or ''
            acc_name = bank_info.get('account_name') or 'Account Holder'
            role = str(bank_info.get('account_role') or bank_info.get('role') or '').lower()
            is_victim = bank_info.get('is_victim_account') is True or role == 'victim'

            if is_victim:
                provider_title = f"{bank_name} (Nodal Legal Cell)"
                desc = f"Outward Remittance Statement Requisition on Complainant A/c {acc_num}"
                bank_pdf_file = f"Notice_Account_Statement_{acc_num}_{case_number}.pdf"
                bank_pdf_path = os.path.join(pdf_dir, bank_pdf_file)
                try:
                    generate_section_94_bnss_pdf(
                        output_path=bank_pdf_path,
                        case_data=master_fir,
                        request_details={
                            "target_provider": provider_title,
                            "items": [
                                f"Complainant Source Account Statement: {acc_num}",
                                "Outward Remittance & UTR Settlement Audit Log",
                                "Certified Account Statement under BSA Section 63"
                            ]
                        }
                    )
                except Exception as e:
                    print(f"[-] Statement PDF Gen Error: {e}")

                legal_requests.append({
                    "request_type": "SECTION_94_BNSS",
                    "target_provider": provider_title,
                    "status": "APPROVED",
                    "pdf_url": f"/api/requests/download/{bank_pdf_file}",
                    "description": desc
                })
                continue
            else:
                provider_title = f"{bank_name} (Nodal Legal Cell)"
                desc = f"Debit Freeze on Accused A/c {acc_num} ({acc_name}, IFSC: {ifsc})"
        else:
            acc_num = str(bank_info)
            provider_title = "Beneficiary Bank Nodal Legal Cell"
            desc = f"Immediate Debit Freeze on Suspect Account {acc_num}"

        bank_pdf_file = f"Notice_Bank_Freeze_{acc_num}_{case_number}.pdf"
        bank_pdf_path = os.path.join(pdf_dir, bank_pdf_file)
        
        try:
            generate_section_94_bnss_pdf(
                output_path=bank_pdf_path,
                case_data=master_fir,
                request_details={
                    "target_provider": provider_title,
                    "items": [
                        f"Debit Freeze on Account Number: {acc_num}",
                        f"Account Holder: {acc_name if isinstance(bank_info, dict) else 'Suspect'}",
                        f"IFSC / Branch: {ifsc if isinstance(bank_info, dict) else 'N/A'}",
                        "Complete Account Statement with IP Hashes & ATM CCTV Footage"
                    ]
                }
            )
        except Exception as e:
            print(f"[-] Bank PDF Gen Error: {e}")

        legal_requests.append({
            "request_type": "SECTION_94_BNSS",
            "target_provider": provider_title,
            "status": "APPROVED",
            "pdf_url": f"/api/requests/download/{bank_pdf_file}",
            "description": desc
        })

    # B. Targeted VPA / UPI Freeze Requisitions (Distinct PDF per VPA)
    for vpa in vpas:
        vpa_pdf_file = f"Notice_UPI_Freeze_{re.sub(r'[^a-zA-Z0-9]', '_', vpa)}_{case_number}.pdf"
        vpa_pdf_path = os.path.join(pdf_dir, vpa_pdf_file)
        
        try:
            generate_section_94_bnss_pdf(
                output_path=vpa_pdf_path,
                case_data=master_fir,
                request_details={
                    "target_provider": "Payment Gateway / NPCI Cyber Nodal Cell",
                    "items": [
                        f"Target UPI VPA: {vpa}",
                        "Immediate Debit Freeze on Linked Merchant Account",
                        "Complete Transaction Settlement Log with IP Hashes"
                    ]
                }
            )
        except Exception as e:
            print(f"[-] VPA PDF Gen Error: {e}")

        legal_requests.append({
            "request_type": "SECTION_94_BNSS",
            "target_provider": "Payment Gateway / NPCI Cyber Cell",
            "status": "APPROVED",
            "pdf_url": f"/api/requests/download/{vpa_pdf_file}",
            "description": f"Freeze VPA {vpa} and obtain nodal merchant settlement statement"
        })

    def _resolve_telecom_carrier(phone_str: str) -> str:
        """Resolve telecom provider dynamically using phonenumbers library."""
        try:
            import phonenumbers
            from phonenumbers import carrier
            clean_num = str(phone_str).strip()
            if not clean_num.startswith('+'):
                if len(clean_num) == 10:
                    clean_num = '+91' + clean_num
                elif len(clean_num) == 12 and clean_num.startswith('91'):
                    clean_num = '+' + clean_num
                else:
                    clean_num = '+91' + clean_num
            parsed = phonenumbers.parse(clean_num)
            c_name = carrier.name_for_number(parsed, "en")
            if c_name:
                c_lower = c_name.lower()
                if 'jio' in c_lower or 'reliance' in c_lower:
                    return "Reliance Jio Infocomm Ltd (Nodal Legal Cell)"
                elif 'airtel' in c_lower or 'bharti' in c_lower:
                    return "Bharti Airtel Ltd (Nodal Legal Compliance Cell)"
                elif 'vodafone' in c_lower or 'idea' in c_lower:
                    return "Vodafone Idea Ltd (Nodal Regulatory & LEA Cell)"
                elif 'bsnl' in c_lower or 'bharat sanchar' in c_lower:
                    return "BSNL (Nodal Cyber Crime Legal Cell)"
                return f"{c_name} (Telecom Nodal Legal Cell)"
        except Exception:
            pass
        return "Telecom Operator Nodal Officer"

    # C. Targeted Telecom CDR & Tower Data Requisitions (Distinct PDF per Phone)
    for phone in phone_numbers:
        phone_pdf_file = f"Notice_Telecom_CDR_{re.sub(r'[^0-9]', '', phone)}_{case_number}.pdf"
        phone_pdf_path = os.path.join(pdf_dir, phone_pdf_file)
        carrier_title = _resolve_telecom_carrier(phone)
        
        try:
            generate_section_94_bnss_pdf(
                output_path=phone_pdf_path,
                case_data=master_fir,
                request_details={
                    "target_provider": carrier_title,
                    "items": [
                        f"Target Mobile Number: {phone}",
                        "CDR with Cell Tower Location Dumps & IMEI History",
                        "Subscriber Registration Form (CAF) & Photo ID Proof"
                    ]
                }
            )
        except Exception as e:
            print(f"[-] Telecom PDF Gen Error: {e}")

        legal_requests.append({
            "request_type": "SECTION_94_BNSS",
            "target_provider": carrier_title,
            "status": "APPROVED",
            "pdf_url": f"/api/requests/download/{phone_pdf_file}",
            "description": f"CDR, Tower Location & CAF Requisition for {phone} ({carrier_title})"
        })

    # D. Targeted Intermediary & Platform Subpoenas (Section 94 BNSS)
    entity_handles = entities.get('online_handles') or []
    emails = entities.get('email_addresses') or []
    regex_handles = re.findall(r'@\w+', complaint_text)
    
    # Merge, deduplicate
    all_handles_lower = set()
    merged_handles = []
    for h in entity_handles + regex_handles:
        if h.lower() not in all_handles_lower:
            merged_handles.append(h)
            all_handles_lower.add(h.lower())
    handles = merged_handles

    comp_lower = complaint_text.lower()
    sub_lower = crime_sub_type.lower()

    # 1. Emergency Section 79(3)(b) IT Act Content Takedown (Only for hosted media/blackmail/leaks)
    is_takedown_needed = (
        "takedown" in comp_lower
        or "blackmail" in comp_lower
        or "sextortion" in sub_lower
        or "leaked video" in comp_lower
        or "objectionable content" in comp_lower
        or ("video" in comp_lower and "video call" not in comp_lower and "call" not in comp_lower)
    )

    if is_takedown_needed:
        takedown_pdf_file = f"Order_Section_79_IT_Act_Takedown_{case_number}.pdf"
        takedown_pdf_path = os.path.join(pdf_dir, takedown_pdf_file)
        handle_str = ", ".join(handles) if handles else "Suspect Account Handle"
        
        try:
            generate_section_79_it_act_takedown_pdf(
                output_path=takedown_pdf_path,
                case_data=master_fir,
                request_details={
                    "target_provider": "Meta Platforms Inc. (Instagram / Facebook) & Google LLC (YouTube)",
                    "items": [
                        f"Target Account / Handle: {handle_str}",
                        "Emergency Removal & Disabling Access to Objectionable Content / Media",
                        "Preserve IP Login Logs & Registration Metadata for 180 days"
                    ]
                }
            )
        except Exception as e:
            print(f"[-] Takedown PDF Gen Error: {e}")

        legal_requests.append({
            "request_type": "SECTION_79_IT_ACT_TAKEDOWN",
            "target_provider": "Meta Platforms & Google LLC Nodal Compliance",
            "status": "APPROVED",
            "pdf_url": f"/api/requests/download/{takedown_pdf_file}",
            "description": f"Emergency Takedown & Blocking Order for objectionable content ({handle_str})"
        })

    # 2. Telegram FZ-LLC Subpoena (Targeted for Telegram handles & group links)
    telegram_targets = [h for h in handles if 't.me' in h.lower() or h.startswith('@')]
    has_telegram = bool(telegram_targets) or "telegram" in comp_lower or "ટેલીગ્રામ" in comp_lower or "t.me" in comp_lower

    if has_telegram:
        tg_target_str = ", ".join(telegram_targets) if telegram_targets else (handles[0] if handles else "Suspect Telegram Account")
        tg_pdf_file = f"Notice_Telegram_Subpoena_{case_number}.pdf"
        tg_pdf_path = os.path.join(pdf_dir, tg_pdf_file)

        try:
            generate_section_94_bnss_pdf(
                output_path=tg_pdf_path,
                case_data=master_fir,
                request_details={
                    "target_provider": "Telegram FZ-LLC (Legal Compliance)",
                    "items": [
                        f"Target Telegram Handle / Channel: {tg_target_str}",
                        "User Account ID, Registration Phone Number & Associated Email",
                        "Channel/Group Admin Creation IP & Login IP Logs with Timestamps & Port Numbers",
                        "Account Preservation under Section 94 BNSS"
                    ]
                }
            )
        except Exception as e:
            print(f"[-] Telegram PDF Gen Error: {e}")

        legal_requests.append({
            "request_type": "PLATFORM_SUBPOENA",
            "target_provider": "Telegram FZ-LLC (Legal Compliance)",
            "status": "APPROVED",
            "pdf_url": f"/api/requests/download/{tg_pdf_file}",
            "description": f"IP Login Logs, User ID & Channel Admin Details for Telegram: {tg_target_str}"
        })

    # 3. Meta Platforms Inc. (WhatsApp / Instagram Subpoena)
    has_whatsapp = "whatsapp" in comp_lower or "meta" in comp_lower or "instagram" in comp_lower
    if has_whatsapp:
        wa_target_str = ", ".join(phone_numbers) if phone_numbers else "Suspect WhatsApp Account"
        wa_pdf_file = f"Notice_WhatsApp_Subpoena_{case_number}.pdf"
        wa_pdf_path = os.path.join(pdf_dir, wa_pdf_file)

        try:
            generate_section_94_bnss_pdf(
                output_path=wa_pdf_path,
                case_data=master_fir,
                request_details={
                    "target_provider": "Meta Platforms Inc. (WhatsApp Legal Compliance)",
                    "items": [
                        f"Target WhatsApp Phone Number / Identifier: {wa_target_str}",
                        "Account Registration Metadata, Linked Devices & Verification IP",
                        "VoIP Video/Voice Call Session Timestamps & Associated IP Logs",
                        "Subscriber Profile & Backup Cloud Metadata"
                    ]
                }
            )
        except Exception as e:
            print(f"[-] WhatsApp PDF Gen Error: {e}")

        legal_requests.append({
            "request_type": "PLATFORM_SUBPOENA",
            "target_provider": "Meta Platforms Inc. (WhatsApp Legal Compliance)",
            "status": "APPROVED",
            "pdf_url": f"/api/requests/download/{wa_pdf_file}",
            "description": f"VoIP Session Logs, Device Registration & IPs for WhatsApp Number(s): {wa_target_str}"
        })

    # 4. Google LLC Subpoena (Targeted for Google Drive links & Gmail addresses)
    google_targets = [h for h in handles if 'drive.google.com' in h.lower() or 'google' in h.lower()]
    gmail_targets = [em for em in emails if 'gmail.com' in em.lower()]
    has_google = bool(google_targets) or bool(gmail_targets) or "google" in comp_lower or "gmail" in comp_lower

    if has_google:
        g_items_str = ", ".join(google_targets + gmail_targets) if (google_targets or gmail_targets) else "Google Account / Drive Link"
        google_pdf_file = f"Notice_Google_Subpoena_{case_number}.pdf"
        google_pdf_path = os.path.join(pdf_dir, google_pdf_file)

        try:
            generate_section_94_bnss_pdf(
                output_path=google_pdf_path,
                case_data=master_fir,
                request_details={
                    "target_provider": "Google LLC (Legal Compliance)",
                    "items": [
                        f"Target Identifier(s): {g_items_str}",
                        "Google Drive File Uploader Account ID & Access Log IP Timestamps",
                        "Gmail Account Registration IP, Recovery Email & Linked Phone Number",
                        "Account Preservation under Section 94 BNSS / BSA Section 63"
                    ]
                }
            )
        except Exception as e:
            print(f"[-] Google PDF Gen Error: {e}")

        legal_requests.append({
            "request_type": "PLATFORM_SUBPOENA",
            "target_provider": "Google LLC (Legal Compliance)",
            "status": "APPROVED",
            "pdf_url": f"/api/requests/download/{google_pdf_file}",
            "description": f"Drive Uploader Logs, Access IPs & Account Registration for: {g_items_str}"
        })

    # Fallback if no specific requests built
    if not legal_requests:
        default_pdf_file = f"Notice_Section_94_BNSS_{case_number}.pdf"
        default_pdf_path = os.path.join(pdf_dir, default_pdf_file)
        try:
            generate_section_94_bnss_pdf(
                output_path=default_pdf_path,
                case_data=master_fir,
                request_details={
                    "target_provider": "Nodal Compliance Officer",
                    "items": [f"Legal Requisition for {crime_sub_type}"]
                }
            )
        except Exception as e:
            pass

        legal_requests.append({
            "request_type": "SECTION_94_BNSS",
            "target_provider": "Nodal Compliance Officer",
            "status": "APPROVED",
            "pdf_url": f"/api/requests/download/{default_pdf_file}",
            "description": f"Section 94 BNSS Legal Requisition for {crime_sub_type}"
        })

    summary_text = (
        f"Investigation path successfully compiled for Case {case_number}. "
        f"Grounding verified across BNS Sections ({sec_str}) and BSA Section 63 Evidence rules. "
        f"Found {len(cross_matches)} cross-case matches linking to past complaints. "
        f"Section 94 BNSS Turnkey PDF generated for immediate service provider dispatch."
    )
    if evaluation_degraded and unresolved_feedback:
        summary_text += (
            f" [QUALITY WARNING: Evaluator could not fully resolve: {'; '.join(unresolved_feedback)}. "
            "Manual verification by Investigating Officer is recommended.]"
        )

    print(f"[+] Synthesis Node Completed: Master FIR and {len(legal_requests)} distinct legal notice PDFs ready.")
    
    return {
        "master_fir_details": master_fir,
        "investigation_steps": steps,
        "legal_requests_to_generate": legal_requests,
        "summary": summary_text
    }
